### ISSUE TITLE
Custom primary key type instead of guid

### ISSUE THREAD

**Issue by n3v3rf411** [buckless/requelize#28]
Hi!

Great work on this library! I noticed that the primary key's type is always overridden to guid. Would it be possible to customize its type?

Thanks!

**Comment by gjuchault** [comment]
Hi !

Indeed I didn't make requelize with other primary key type in mind
This is mainly because all the relationships works with guid.

What would you put as primary key ?

**Comment by n3v3rf411** [comment]
I have data that I scrape from other another system that have integer primary keys. I want them to use that primary key as well when saving to the database. On my other tables, GUID primary keys are good.

At the moment I resort to converting those integers to GUID. This seems to be an counter-intuitive to how GUID is supposed to be unique but it does work in my case for now.

**Comment by gjuchault** [comment]
@n3v3rf411 I did do some stuff in a pull-request (#30).
Can you look into https://github.com/buckless/requelize/blob/a4b4bf77b040fa08bc3607ff86abc3139d5925af/test/test.issue28.js and tell me if that would be enough (ie. having `id` being integer). I'll release if that's ok :)

**Comment by gjuchault** [comment]
Fixed by #30, will be released soon :)
