### ISSUE TITLE
Question by code

### ISSUE THREAD

**Issue by Riim** [buckless/requelize#33]
I can't understand why need this [line](https://github.com/buckless/requelize/blob/a9f7e7a9a2df1cbb9b0cdcf5a64b842c31956891/lib/model/model.js#L123). And if there really can be an array then it may be more correctly to write so:
```js
Joi.array().optional().allow(null).items(idType)
```
?

**Comment by gjuchault** [comment]
This line is there to allow an array of ids to be a valid field data for a relationship.

A relationship can be either a guid (`idType.optional().allow(null)`) or an array of guid (`Joi.array().items(idType.optional().allow(null))`).

You have an example of a localKey being a guid [here](https://github.com/buckless/requelize/blob/a9f7e7a9a2df1cbb9b0cdcf5a64b842c31956891/test/test.belongsTo.js#L32)

You have an example of a localKey being an array of guid [here](https://github.com/buckless/requelize/blob/a9f7e7a9a2df1cbb9b0cdcf5a64b842c31956891/test/test.saveAll.js#L63)

Your line is an optional array (an array or null) that contains guids. This can not do what my line does
